const wordCategories = {
  "Animales": ["Perro", "Gato", "Elefante", "León", "Jirafa", "Tigre", "Oso", "Pingüino", "Mono", "Cebra"],
  "Comidas": ["Pizza", "Hamburguesa", "Sushi", "Taco", "Ensalada", "Pasta", "Sopa", "Helado", "Paella", "Curry"],
  "Frutas": ["Manzana", "Plátano", "Fresa", "Naranja", "Uva", "Piña", "Mango", "Sandía", "Kiwi", "Pera"],
  "Profesiones": ["Médico", "Profesor", "Bombero", "Policía", "Ingeniero", "Artista", "Chef", "Piloto", "Abogado", "Científico"],
  "Deportes": ["Fútbol", "Baloncesto", "Tenis", "Béisbol", "Natación", "Voleibol", "Golf", "Boxeo", "Ciclismo", "Atletismo"],
  "Países": ["España", "México", "Argentina", "Japón", "Italia", "Canadá", "Brasil", "Australia", "Egipto", "China"],
  "Instrumentos Musicales": ["Guitarra", "Piano", "Violín", "Batería", "Trompeta", "Flauta", "Saxofón", "Arpa", "Bajo", "Acordeón"],
  "Vehículos": ["Coche", "Bicicleta", "Avión", "Barco", "Tren", "Motocicleta", "Autobús", "Helicóptero", "Submarino", "Camión"],
  "Colores": ["Rojo", "Azul", "Verde", "Amarillo", "Naranja", "Morado", "Negro", "Blanco", "Rosa", "Marrón"],
  "Partes del Cuerpo": ["Cabeza", "Brazo", "Pierna", "Ojo", "Nariz", "Boca", "Mano", "Pie", "Corazón", "Cerebro"],
  "Ropa": ["Camisa", "Pantalón", "Vestido", "Zapato", "Sombrero", "Chaqueta", "Falda", "Calcetines", "Gafas", "Guantes"],
  "Objetos de la Casa": ["Silla", "Mesa", "Cama", "Sofá", "Lámpara", "Televisión", "Espejo", "Reloj", "Armario", "Nevera"],
  "Fenómenos Naturales": ["Lluvia", "Nieve", "Viento", "Sol", "Terremoto", "Tornado", "Huracán", "Volcán", "Arcoíris", "Tsunami"],
  "Películas Famosas": ["Titanic", "Star Wars", "Jurassic Park", "El Padrino", "Avatar", "Matrix", "Forrest Gump", "Pulp Fiction", "E.T.", "Casablanca"],
  "Superhéroes": ["Superman", "Batman", "Spiderman", "Iron Man", "Capitán América", "Thor", "Hulk", "Wonder Woman", "Aquaman", "Flash"],
  "Herramientas": ["Martillo", "Destornillador", "Sierra", "Taladro", "Llave inglesa", "Alicates", "Cinta métrica", "Nivel", "Tornillo", "Clavo"],
  "Bebidas": ["Agua", "Café", "Té", "Leche", "Jugo", "Refresco", "Vino", "Cerveza", "Limonada", "Chocolate caliente"],
  "Planetas": ["Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno"],
  "Figuras Geométricas": ["Círculo", "Cuadrado", "Triángulo", "Rectángulo", "Pentágono", "Hexágono", "Estrella", "Cubo", "Esfera", "Cilindro"],
  "Emociones": ["Alegría", "Tristeza", "Enojo", "Miedo", "Sorpresa", "Amor", "Asco", "Vergüenza", "Orgullo", "Calma"],
  "Verduras": ["Zanahoria", "Brócoli", "Tomate", "Lechuga", "Patata", "Cebolla", "Pimiento", "Espinaca", "Calabacín", "Berenjena"],
  "Muebles": ["Escritorio", "Estantería", "Sillón", "Cómoda", "Mesita de noche", "Vitrina", "Taburete", "Banco", "Perchero", "Mecedora"],
  "Asignaturas Escolares": ["Matemáticas", "Historia", "Ciencias", "Lengua", "Geografía", "Arte", "Música", "Química", "Física", "Biología"],
  "Flores": ["Rosa", "Tulipán", "Margarita", "Girasol", "Lirio", "Orquídea", "Clavel", "Amapola", "Jazmín", "Violeta"],
  "Postres": ["Tarta", "Flan", "Galleta", "Mousse", "Brownie", "Crepe", "Gofre", "Tiramisú", "Pudin", "Magdalena"],
  "Clima": ["Nublado", "Soleado", "Ventoso", "Tormenta", "Niebla", "Granizo", "Humedad", "Sequía", "Monzón", "Helada"],
  "Partes de un Coche": ["Volante", "Rueda", "Motor", "Puerta", "Ventana", "Faro", "Asiento", "Freno", "Maletero", "Espejo"],
  "Géneros Musicales": ["Rock", "Pop", "Jazz", "Clásica", "Reggaetón", "Electrónica", "Hip Hop", "Salsa", "Flamenco", "Blues"],
  "Animales Marinos": ["Ballena", "Delfín", "Tiburón", "Pulpo", "Calamar", "Medusa", "Foca", "Cangrejo", "Langosta", "Estrella de mar"],
  "Idiomas": ["Español", "Inglés", "Francés", "Alemán", "Chino", "Japonés", "Ruso", "Árabe", "Portugués", "Italiano"],
  "Cosas de Baño": ["Inodoro", "Ducha", "Lavabo", "Toalla", "Jabón", "Champú", "Esponja", "Bañera", "Grifo", "Papel higiénico"],
  "Personajes de Videojuegos": ["Mario", "Zelda", "Sonic", "Pikachu", "Lara Croft", "Pac-Man", "Kratos", "Master Chief", "Donkey Kong", "Cloud Strife"],
  "Seres Mitológicos": ["Dragón", "Unicornio", "Fénix", "Centauro", "Sirena", "Minotauro", "Grifo", "Cíclope", "Hidra", "Pegaso"],
  "Términos de Internet": ["Meme", "Viral", "Hashtag", "Selfie", "Streaming", "Podcast", "Emoji", "Spoiler", "Clickbait", "Influencer"],
  "Supervillanos": ["Joker", "Darth Vader", "Thanos", "Voldemort", "Magneto", "Loki", "Lex Luthor", "Venom", "Green Goblin", "Catwoman"],
  "Cosas Pegajosas": ["Miel", "Chicle", "Pegamento", "Cinta adhesiva", "Caramelo", "Mermelada", "Slime", "Sirope", "Resina", "Barro"],
  "Sonidos": ["Explosión", "Susurro", "Campana", "Aplauso", "Ladrido", "Goteo", "Timbre", "Ronquido", "Estornudo", "Risa"],
  "Cosas que se Estiran": ["Goma elástica", "Chicle", "Masa de pizza", "Calcetín", "Tirachinas", "Acordeón", "Jersey de lana", "Muelle", "Globo", "Telaraña"],
  "Marcas de Lujo": ["Rolex", "Gucci", "Ferrari", "Chanel", "Louis Vuitton", "Porsche", "Prada", "Lamborghini", "Hermès", "Versace"],
  "Palabras Raras y Graciosas": ["Pachorra", "Gamberro", "Zarrapastroso", "Chirimbolo", "Pelele", "Trasto", "Cachivache", "Pantufla", "Botarate", "Mangurrián"]
};
