// Este archivo contiene todas las categorías y palabras para el juego Imposter Who?
// Las palabras están ahora divididas por dificultad dentro de cada categoría.
// Cada categoría contiene más de 100 palabras comunes.

const WORD_CATEGORIES = {
    "Objetos cotidianos": {
        "easy": ["Silla", "Mesa", "Cama", "Sofá", "Puerta", "Ventana", "Lámpara", "Vaso", "Plato", "Tenedor", "Cuchara", "Cuchillo", "Reloj", "Espejo", "Libro", "Llave", "Móvil", "Mando", "Gafas", "Peine", "Cepillo", "Jabón", "Toalla", "Papel", "Lápiz", "Bolígrafo", "Tijera", "Puerta", "Cama", "Almohada", "Manta", "Caja", "Botella", "Bolsa", "Zapato"],
        "medium": ["Televisión", "Ordenador", "Teléfono", "Microondas", "Nevera", "Lavadora", "Horno", "Ducha", "Armario", "Alfombra", "Cortina", "Aspiradora", "Plancha", "Tostadora", "Batidora", "Cafetera", "Hervidor", "Secador de pelo", "Escoba", "Fregona", "Cubo", "Cojín", "Sartén", "Olla", " Paraguas", "Mochila", "Cartera", "Monedero", "Batería", "Cargador", "Auriculares", "Altavoz", "Impresora", "Teclado", "Ratón"],
        "hard": ["Deshumidificador", "Humidificador", "Purificador de aire", "Robot aspirador", "Freidora de aire", "Olla de cocción lenta", "Procesador de alimentos", "Tabla de planchar", "Tendedero", "Cesto de la ropa", "Sacacorchos", "Abrelatas", "Rallador", "Espátula", "Colador", "Embudo", "Mortero", "Rodillo", "Exprimidor", "Báscula", "Temporizador", "Vaporeira", "Sandwichera", "Gofrera", "Licuadora", "Picadora", "Yogurtera", "Panificadora", "Robot de cocina", "Campana extractora", "Lavavajillas", "Calefactor", "Termostato", "Ventilador", "Estufa", "Taladro", "Martillo", "Destornillador", "Alicates", "Sierra", "Cinta métrica", "Nivel", "Escalera", "Alargador", "Bombilla", "Pila", "Router", "Webcam", "Micrófono", "Tableta", "Lector de libros electrónicos", "Puzle", "Baraja de cartas", "Dados", "Álbum de fotos", "Marco de fotos", "Globo terráqueo", "Pizarra", "Corcho", "Chincheta", "Clip", "Grapadora", "Pegamento", "Agenda", "Calendario", "Llavero", "Botiquín", "Termómetro", "Tirita", "Venda", "Algodón", "Pastilla", "Jarabe", "Crema"]
    },
    "Personas famosas": {
        "easy": ["Messi", "Shakira", "Einstein", "Picasso", "Michael Jackson", "Madonna", "Beyoncé", "Taylor Swift", "Cristiano Ronaldo", "LeBron James", "Tom Hanks", "Leonardo DiCaprio", "Brad Pitt", "Angelina Jolie", "Will Smith", "Oprah Winfrey", "Elon Musk", "Bill Gates", "Steve Jobs", "The Rock", "Queen Elizabeth", "Obama", "Trump", "Putin", "Papa Francisco"],
        "medium": ["Leonardo da Vinci", "Cleopatra", "Napoleón", "Julio César", "Alejandro Magno", "Juana de Arco", "Isaac Newton", "Galileo Galilei", "Marie Curie", "Cristóbal Colón", "Martin Luther King Jr.", "Nelson Mandela", "Mahatma Gandhi", "Winston Churchill", "Mozart", "Beethoven", "Bach", "Shakespeare", "Cervantes", "Van Gogh", "Dalí", "Frida Kahlo", "Charles Chaplin", "Marilyn Monroe", "Elvis Presley"],
        "hard": ["Aristóteles", "Platón", "Sócrates", "Confucio", "Gengis Kan", "Atila", "Carlomagno", "Nikola Tesla", "Alan Turing", "Rosalind Franklin", "Hipatia de Alejandría", "Simone de Beauvoir", "Virginia Woolf", "Federico García Lorca", "Vincent van Gogh", "Rembrandt", "Velázquez", "Goya", "Chopin", "Vivaldi", "Tchaikovsky", "Hitchcock", "Kubrick", "Tarantino", "Scorsese", "Spielberg", "Copernicus", "Darwin", "Freud", "Jung", "Kant", "Nietzsche", "Marx", "Voltaire", "Rousseau", "Che Guevara", "Fidel Castro", "Mao Zedong", "Indira Gandhi", "Margaret Thatcher", "Golda Meir", "Eva Perón", "Malala Yousafzai", "Greta Thunberg", "Princesa Diana", "Grace Kelly", "Pelé", "Maradona", "Muhammad Ali", "Michael Jordan", "Usain Bolt", "Serena Williams", "Roger Federer", "Rafael Nadal", "Michael Phelps", "Simone Biles", "Tiger Woods", "Wayne Gretzky", "Tom Brady", "Babe Ruth", "Jesse Owens", "Carl Lewis", "Eddy Merckx", "Lance Armstrong", "Valentino Rossi", "Michael Schumacher", "Ayrton Senna", "Niki Lauda", "Garry Kasparov", "Bobby Fischer", "Magnus Carlsen", "Judit Polgár", "Anatoly Karpov", "Mijaíl Tal", "José Raúl Capablanca", "Paul Morphy", "Emanuel Lasker", "Wilhelm Steinitz", "Akira Kurosawa", "Ingmar Bergman", "Federico Fellini", "Luis Buñuel", "Pedro Almodóvar", "Guillermo del Toro", "Alfonso Cuarón", "Alejandro González Iñárritu", "Bong Joon-ho", "Hayao Miyazaki", "Isao Takahata", "Satoshi Kon", "Yasujirō Ozu", "Kenji Mizoguchi", "Mikio Naruse"]
    },
    "Comidas y bebidas": {
        "easy": ["Pan", "Agua", "Leche", "Huevo", "Queso", "Manzana", "Plátano", "Arroz", "Pollo", "Tomate", "Patata", "Sal", "Azúcar", "Sopa", "Zumo", "Carne", "Pescado", "Naranja", "Limón", "Uvas", "Fresa", "Cebolla", "Ajo", "Aceite", "Galleta", "Café", "Té", "Vino", "Cerveza", "Refresco", "Chocolate", "Helado", "Pasta", "Pizza", "Hamburguesa"],
        "medium": ["Sushi", "Paella", "Taco", "Ensalada", "Lentejas", "Yogur", "Miel", "Mantequilla", "Harina", "Pimienta", "Zanahoria", "Brócoli", "Espinaca", "Pimiento", "Maíz", "Champiñón", "Jamón", "Salchicha", "Bacon", "Chorizo", "Salami", "Atún", "Salmón", "Bacalao", "Merluza", "Tortilla", "Croqueta", "Churro", "Gazpacho", "Salmorejo", "Fabada", "Cocido", "Guiso", "Asado", "Sándwich"],
        "hard": ["Quinoa", "Tofu", "Seitán", "Hummus", "Guacamole", "Ceviche", "Risotto", "Fondue", "Kimchi", "Kombucha", "Edamame", "Chía", "Açai", "Wasabi", "Jengibre", "Cuscús", "Falafel", "Turrón", "Mazapán", "Pisto", "Migas", "Pulpo a la gallega", "Calamares", "Gambas", "Mejillones", "Almejas", "Ostras", "Percebes", "Anchoas", "Boquerones", "Sardinas", "Bogavante", "Langosta", "Nécora", "Centollo", "Vieira", "Zamburiña", "Navaja", "Berberecho", "Erizo de mar", "Alga", "Wakame", "Nori", "Kombu", "Gofio", "Polenta", "Sémola", "Bulgur", "Mijo", "Trigo sarraceno", "Espelta", "Kamut", "Triticale", "Centeno", "Cebada", "Avena", "Lichi", "Maracuyá", "Pitahaya", "Carambola", "Rambután", "Mangostán", "Durian", "Jackfruit", "Yaca", "Chirimoya", "Guanábana", "Noni", "Azafrán", "Cardamomo", "Cúrcuma", "Curry", "Pimentón", "Comino", "Clavo", "Nuez moscada", "Canela", "Vainilla", "Anís", "Hinojo", "Eneldo", "Estragón", "Mejorana", "Orégano", "Romero", "Salvia", "Tomillo", "Albahaca", "Menta", "Hierbabuena", "Cilantro", "Perejil", "Cebollino", "Laurel"]
    },
    "Marcas y logotipos": {
        "easy": ["Coca-Cola", "Nike", "Apple", "Google", "Amazon", "McDonald's", "Adidas", "Toyota", "Samsung", "Disney", "Lego", "Ikea", "Ferrari", "Microsoft", "Netflix", "Starbucks", "Ford", "Sony", "Pepsi", "Zara", "Gucci", "Louis Vuitton", "Chanel", "Rolex", "BMW"],
        "medium": ["Mercedes-Benz", "Audi", "Volkswagen", "Porsche", "Honda", "Hyundai", "Nissan", "Intel", "Nvidia", "HP", "Dell", "Canon", "Nikon", "Panasonic", "LG", "Philips", "Bosch", "Dyson", "L'Oréal", "Gillette", "Colgate", "Pampers", "Nestlé", "Danone", "Kellogg's", "Red Bull", "Heineken", "Budweiser", "Visa", "Mastercard", "American Express", "PayPal", "Boeing", "Airbus", "Ryanair", "Iberia", "Facebook", "Instagram", "WhatsApp", "Twitter", "TikTok", "YouTube", "Spotify", "Uber", "Airbnb", "Tesla", "SpaceX"],
        "hard": ["Unilever", "Procter & Gamble", "Johnson & Johnson", "Pfizer", "Bayer", "Oracle", "SAP", "Adobe", "Salesforce", "Qualcomm", "AMD", "Asus", "Lenovo", "Acer", "Razer", "Logitech", "Sennheiser", "JBL", "Bose", "Harman Kardon", "Bang & Olufsen", "Miele", "Siemens", "Electrolux", "Whirlpool", "Tefal", "Krups", "Nespresso", "Lavazza", "Illy", "Segafredo", "Starbucks", "Costa Coffee", "Dunkin'", "Burger King", "KFC", "Subway", "Pizza Hut", "Domino's", "Taco Bell", "Wendy's", "Chipotle", "Panda Express", "Five Guys", "In-N-Out", "Shake Shack", "Carl's Jr.", "Hardee's", "Jack in the Box", "Popeyes", "Arby's", "Dairy Queen", "Sonic", "Whataburger", "Chick-fil-A", "Zaxby's", "Bojangles'", "Church's Chicken", "Wingstop", "Little Caesars", "Papa John's", "Marco's Pizza", "Sbarro", "Cinnabon", "Auntie Anne's", "Jamba", "Baskin-Robbins", "Häagen-Dazs", "Ben & Jerry's", "Magnum", "Cornetto", "Frigo", "Kalise", "La Menorquina", "Royne", "Camy", "Miko", "Carte d'Or", "Viennetta", "Solero", "Twister", "Calippo", "Drácula", "Frigopié", "Frigodedo", "Colajet", "Negritón", "Fantasmikos", "Polo", "Flash", "Burmar Flax", "Chupa Chups", "Smint", "Trident", "Orbit", "Five", "Clix", "Bubbaloo", "Boomer", "Cheiw", "Sugus", "Solano", "Pez", "Haribo", "Fini", "Vidal", "Roypas", "Damel", "Fiesta", "Kojak", "Lolipop", "Piruleta"]
    },
    "Colores y formas": {
        "easy": ["Rojo", "Azul", "Verde", "Amarillo", "Negro", "Blanco", "Naranja", "Morado", "Rosa", "Marrón", "Gris", "Círculo", "Cuadrado", "Triángulo", "Rectángulo", "Estrella", "Corazón", "Línea", "Punto", "Cruz", "Flecha", "Rayo", "Luna", "Sol", "Nube"],
        "medium": ["Violeta", "Cian", "Magenta", "Turquesa", "Dorado", "Plateado", "Beige", "Índigo", "Lavanda", "Salmón", "Óvalo", "Rombo", "Pentágono", "Hexágono", "Octógono", "Cilindro", "Cubo", "Esfera", "Pirámide", "Cono", "Prisma", "Espiral", "Hélice", "Zigzag", "Onda"],
        "hard": ["Bermellón", "Carmín", "Escarlata", "Granate", "Fucsia", "Malva", "Púrpura", "Añil", "Azabache", "Ébano", "Marfil", "Crema", "Caqui", "Ocre", "Siena", "Terracota", "Verde oliva", "Verde esmeralda", "Verde jade", "Aguamarina", "Celeste", "Azul cobalto", "Azul marino", "Azul Prusia", "Sepia", "Trapecio", "Paralelogramo", "Deltoide", "Heptágono", "Eneágono", "Decágono", "Dodecágono", "Icosaedro", "Dodecaedro", "Octaedro", "Tetraedro", "Toroide", "Elipsoide", "Paraboloide", "Hiperboloide", "Catenoide", "Helicoide", "Cinta de Möbius", "Botella de Klein", "Esponja de Menger", "Copo de nieve de Koch", "Triángulo de Sierpinski", "Conjunto de Mandelbrot", "Fractal", "Teselación", "Polígono", "Poliedro", "Vértice", "Arista", "Cara", "Ángulo", "Radio", "Diámetro", "Perímetro", "Área", "Volumen", "Curva", "Tangente", "Secante", "Cuerda", "Arco", "Sector", "Segmento", "Corona", "Lúnula", "Hipocicloide", "Epicicloide", "Cardioide", "Nefroide", "Astroide", "Deltoide", "Lemniscata", "Cisoide", "Estrofoide", "Concoide", "Óvalo de Cassini", "Folio de Descartes", "Trisectriz de Maclaurin", "Cuadratriz de Hipias", "Espiral de Arquímedes", "Espiral logarítmica", "Espiral de Fermat", "Espiral hiperbólica", "Lituus", "Clotoide", "Hélice cónica", "Hélice esférica", "Loxodrómica", "Curva de Peano", "Curva de Hilbert", "Curva del dragón", "Árbol de Pitágoras", "Alfombra de Sierpinski"]
    },
    "Países y ciudades": {
        "easy": ["España", "Francia", "Italia", "Portugal", "Alemania", "Reino Unido", "China", "Japón", "Rusia", "Estados Unidos", "Canadá", "México", "Brasil", "Argentina", "Australia", "Madrid", "París", "Londres", "Roma", "Berlín", "Moscú", "Pekín", "Tokio", "Nueva York", "Los Ángeles"],
        "medium": ["India", "Egipto", "Sudáfrica", "Grecia", "Turquía", "Suecia", "Noruega", "Suiza", "Países Bajos", "Bélgica", "Corea del Sur", "Tailandia", "Vietnam", "Colombia", "Perú", "Chile", "Lisboa", "Dublín", "Ámsterdam", "Bruselas", "Viena", "Praga", "Atenas", "Estambul", "Sídney"],
        "hard": ["Bután", "Kiribati", "Liechtenstein", "Nauru", "San Marino", "Tuvalu", "Vanuatu", "Andorra", "Brunéi", "Yibuti", "Esuatini", "Lesoto", "Maldivas", "Seychelles", "Timor Oriental", "Katmandú", "Thimphu", "Taskent", "Asjabad", "Dusambé", "Biskek", "Nursultán", "Ulán Bator", "Pyongyang", "Vientián", "Nom Pen", "Naipyidó", "Daca", "Colombo", "Malé", "Kabul", "Teherán", "Bagdad", "Damasco", "Ammán", "Beirut", "Saná", "Mascate", "Abu Dabi", "Doha", "Kuwait", "Manama", "Riad", "Trípoli", "Argel", "Túnez", "Rabat", "Nuakchot", "Dakar", "Bamako", "Uagadugú", "Niamey", "Yamena", "Jartum", "Yuba", "Adís Abeba", "Mogadiscio", "Nairobi", "Kampala", "Kigali", "Dodoma", "Lusaka", "Harare", "Maputo", "Antananarivo", "Port Louis", "Victoria", "Moroni", "Windhoek", "Gaborone", "Maseru", "Mbabane", "Pretoria", "Luanda", "Kinsasa", "Brazzaville", "Libreville", "Yaundé", "Abuya", "Acra", "Yamusukro", "Monrovia", "Freetown", "Conakri", "Bisáu", "Banjul", "Praia", "Santo Tomé", "Malabo", "Georgetown", "Paramaribo", "Cayena", "Asunción", "Montevideo", "Sucre", "Quito", "Bogotá", "Caracas", "La Habana", "Kingston", "Puerto Príncipe", "Santo Domingo", "San Juan", "Nassau", "Belmopán", "Ciudad de Guatemala", "San Salvador", "Tegucigalpa", "Managua", "San José", "Ciudad de Panamá", "Wellington", "Canberra", "Port Moresby", "Suva", "Apia", "Nukualofa", "Port Vila", "Honiara", "Palikir", "Ngerulmud", "Yaren", "Funafuti", "Tarawa Sur", "Majuro", "Reikiavik", "Oslo", "Estocolmo", "Helsinki", "Copenhague", "Tallin", "Riga", "Vilna", "Minsk", "Kiev", "Chisináu", "Tiflis", "Ereván", "Bakú"]
    },
    "Emociones y sentimientos": {
        "easy": ["Amor", "Felicidad", "Tristeza", "Miedo", "Ira", "Alegría", "Pena", "Enojo", "Risa", "Llanto", "Sorpresa", "Asco", "Calma", "Paz", "Aburrimiento", "Hambre", "Sed", "Sueño", "Cansancio", "Dolor", "Placer", "Deseo", "Odio", "Envidia", "Celos"],
        "medium": ["Orgullo", "Vergüenza", "Culpa", "Arrepentimiento", "Esperanza", "Desesperación", "Ansiedad", "Angustia", "Estrés", "Euforia", "Melancolía", "Nostalgia", "Soledad", "Curiosidad", "Confusión", "Confianza", "Duda", "Seguridad", "Valentía", "Cobardía", "Gratitud", "Admiración", "Respeto", "Desprecio", "Indiferencia"],
        "hard": ["Apatía", "Entusiasmo", "Motivación", "Satisfacción", "Frustración", "Decepción", "Alivio", "Consuelo", "Compasión", "Empatía", "Simpatía", "Antipatía", "Cariño", "Afecto", "Ternura", "Pasión", "Obsesión", "Adoración", "Devoción", "Éxtasis", "Júbilo", "Regocijo", "Aflicción", "Lamento", "Duelo", "Pesar", "Remordimiento", "Humildad", "Soberbia", "Vanidad", "Modestia", "Timidez", "Audacia", "Osadía", "Temeridad", "Prudencia", "Cautela", "Paciencia", "Impaciencia", "Perseverancia", "Tenacidad", "Resignación", "Aceptación", "Negación", "Optimismo", "Pesimismo", "Cinismo", "Idealismo", "Realismo", "Escepticismo", "Fe", "Asertividad", "Sumisión", "Agresividad", "Hostilidad", "Amabilidad", "Cordialidad", "Generosidad", "Egoísmo", "Altruismo", "Solidaridad", "Compañerismo", "Amistad", "Lealtad", "Traición", "Rencor", "Resentimiento", "Perdón", "Reconciliación", "Armonía", "Discordia", "Fascinación", "Encanto", "Desencanto", "Ilusión", "Desilusión", "Histeria", "Pánico", "Fobia", "Paranoia", "Anhelo", "Añoranza", "Morriña", "Saudade", "Desasosiego", "Inquietud", "Zozobra", "Desazón", "Estupor", "Perplejidad", "Asombro", "Estupefacción", "Conmoción", "Sobresalto", "Susto", "Pavor", "Terror", "Horror", "Espanto", "Furia", "Rabia", "Cólera", "Exasperación", "Indignación", "Irritación", "Fastidio", "Hastío", "Tedio", "Desgana", "Ganas", "Alegría", "Contento", "Dicha", "Gozo", "Alborozo", "Entusiasmo"]
    },
    "Aficiones y actividades": {
        "easy": ["Leer", "Correr", "Cantar", "Bailar", "Pintar", "Dibujar", "Cocinar", "Jugar", "Ver la tele", "Escuchar música", "Dormir", "Comer", "Beber", "Hablar", "Andar", "Nadar", "Viajar", "Comprar", "Limpiar", "Trabajar", "Estudiar", "Escribir", "Reír", "Llorar", "Soñar"],
        "medium": ["Jardinería", "Ajedrez", "Senderismo", "Fotografía", "Cine", "Teatro", "Conciertos", "Museos", "Exposiciones", "Deporte", "Gimnasio", "Yoga", "Pilates", "Meditación", "Mindfulness", "Videojuegos", "Juegos de mesa", "Puzles", "Manualidades", "Bricolaje", "Coleccionismo", "Filatelia", "Numismática", "Modelismo", "Maquetas"],
        "hard": ["Origami", "Papiroflexia", "Caligrafía", "Lettering", "Scrapbooking", "Patchwork", "Ganchillo", "Crochet", "Punto de cruz", "Bordado", "Macramé", "Cerámica", "Alfarería", "Escultura", "Talla de madera", "Grabado", "Serigrafía", "Litografía", "Xilografía", "Cianotipia", "Revelado fotográfico", "Acuarela", "Óleo", "Acrílico", "Pastel", "Carboncillo", "Tinta china", "Cómic", "Manga", "Animación", "Stop motion", "Cine experimental", "Cortometraje", "Documental", "Guion", "Dramaturgia", "Poesía", "Novela", "Relato corto", "Ensayo", "Biografía", "Autobiografía", "Blog", "Podcast", "Streaming", "Vlogging", "Creación de contenido", "Programación", "Robótica", "Electrónica", "Impresión 3D", "Diseño gráfico", "Diseño web", "Diseño de interiores", "Diseño de moda", "Patronaje", "Costura", "Tejido", "Hilado", "Tintado", "Restauración de muebles", "Tapicería", "Marquetería", "Ebanistería", "Forja", "Herrería", "Joyería", "Orfebrería", "Vidriería", "Soplado de vidrio", "Enología", "Sumillería", "Cata de vinos", "Cata de cervezas", "Cata de aceites", "Cata de cafés", "Cata de tés", "Cata de chocolates", "Barismo", "Coctelería", "Mixología", "Gastronomía molecular", "Cocina de vanguardia", "Cocina tradicional", "Repostería creativa", "Panadería artesanal", "Huerto urbano", "Permacultura", "Apicultura", "Lombricultura", "Acuaponía", "Hidroponía", "Bonsái", "Ikebana", "Kokedama", "Terrarios", "Jardines verticales", "Observación de aves", "Ornitología", "Astronomía", "Astrología", "Tarot", "Runas", "Quiromancia", "Grafología", "Genealogía", "Heráldica", "Vexilología", "Geocaching", "Urbex", "Escape room", "Juegos de rol", "LARP", "Wargames", "Cosplay", "Recreación histórica"]
    },
    "Cultura de internet": {
        "easy": ["Meme", "Like", "Selfie", "Emoji", "Hashtag", "Viral", "Influencer", "Youtuber", "Streamer", "Gamer", "Blog", "Vlog", "Podcast", "App", "Web", "Link", "Email", "Chat", "Foro", "Red social", "Facebook", "Instagram", "Twitter", "TikTok", "WhatsApp"],
        "medium": ["Streaming", "Follower", "Hater", "Trol", "Spoiler", "Clickbait", "Fake news", "Post", "Tweet", "Story", "Reel", "Directo", "En vivo", "Online", "Offline", "Wifi", "Internet", "Navegador", "Buscador", "Google", "Wikipedia", "Amazon", "Netflix", "Spotify", "Uber"],
        "hard": ["Criptomoneda", "NFT", "Blockchain", "Metaverso", "Realidad virtual", "Realidad aumentada", "Inteligencia artificial", "Algoritmo", "Big data", "Nube", "Servidor", "Hosting", "Dominio", "URL", "HTML", "CSS", "JavaScript", "Python", "Java", "C++", "API", "SDK", "Framework", "Librería", "Repositorio", "GitHub", "Stack Overflow", "Reddit", "Discord", "Twitch", "Patreon", "OnlyFans", "Subreddit", "Canal", "Servidor", "Bot", "Mod", "Admin", "Baneo", "Permaban", "Shadowban", "Filtro", "Firewall", "VPN", "Proxy", "Cookie", "Caché", "Bug", "Glitch", "Lag", "Ping", "FPS", "RPG", "MMORPG", "MOBA", "RTS", "FPS", "Sandbox", "Indie", "Early access", "DLC", "Modding", "Speedrun", "Let's Play", "Walkthrough", "Gameplay", "Review", "Unboxing", "Haul", "DIY", "ASMR", "Mukbang", "Challenge", "Tag", "Colaboración", "Sorteo", "Giveaway", "Crowdfunding", "Kickstarter", "GoFundMe", "Petición", "Change.org", "Meme stock", "Stonks", "Diamond hands", "To the moon", "FOMO", "YOLO", "FUD", "HODL", "Shill", "Airdrop", "Fork", "Halving", "Minería", "Staking", "DeFi", "DAO", "Web3", "DApp", "Smart contract", "Token", "Altcoin", "Shitcoin", "Ballena", "Sardina"]
    },
    "Cocina y gastronomía": {
        "easy": ["Sal", "Azúcar", "Aceite", "Harina", "Huevo", "Leche", "Agua", "Fuego", "Cuchillo", "Tenedor", "Cuchara", "Plato", "Vaso", "Sartén", "Olla", "Horno", "Nevera", "Fregadero", "Basura", "Comida", "Bebida", "Postre", "Fruta", "Verdura", "Carne"],
        "medium": ["Pimienta", "Vinagre", "Mostaza", "Kétchup", "Mayonesa", "Mantequilla", "Queso", "Yogur", "Pan", "Arroz", "Pasta", "Lentejas", "Garbanzos", "Patata", "Cebolla", "Ajo", "Tomate", "Lechuga", "Zanahoria", "Pollo", "Pescado", "Cerdo", "Ternera", "Cordero", "Pavo"],
        "hard": ["Azafrán", "Cúrcuma", "Romero", "Albahaca", "Orégano", "Tomillo", "Laurel", "Perejil", "Cilantro", "Comino", "Pimentón", "Nuez moscada", "Clavo", "Canela", "Vainilla", "Jengibre", "Wasabi", "Soja", "Miso", "Dashi", "Sake", "Mirin", "Vinagre de arroz", "Aceite de sésamo", "Salsa de ostras", "Salsa de pescado", "Leche de coco", "Curry", "Garam masala", "Tandoori", "Masala", "Chutney", "Raita", "Lassi", "Naan", "Chapati", "Samosa", "Pakora", "Biryani", "Korma", "Vindaloo", "Tikka masala", "Butter chicken", "Dal", "Palak paneer", "Aloo gobi", "Chole bhature", "Dosa", "Idli", "Vada", "Sambhar", "Uttapam", "Pani puri", "Bhel puri", "Sev puri", "Dahi puri", "Papdi chaat", "Aloo tikki", "Raj kachori", "Kachori", "Dhokla", "Khandvi", "Fafda", "Jalebi", "Gulab jamun", "Rasgulla", "Barfi", "Ladoo", "Peda", "Soan papdi", "Gajar ka halwa", "Kheer", "Payasam", "Falooda", "Kulfi", "Cucharón", "Espumadera", "Batidor", "Rodillo", "Mortero", "Rallador", "Pelador", "Colador", "Embudo", "Exprimidor", "Báscula", "Temporizador", "Tabla de cortar", "Bol", "Fuente", "Bandeja", "Molde", "Papel de horno", "Papel de aluminio", "Film transparente", "Bolsa de congelar", "Tupper", "Fiambrera", "Termo", "Cantimplora", "Petaca", "Sacacorchos", "Abrelatas", "Abrebotellas", "Cascanueces", "Tijeras de cocina", "Afilador", "Chaira", "Mandolina", "Espiralizador", "Pasapurés", "Prensa de ajos", "Cacillo", "Cazo", "Wok", "Paellera", "Plancha", "Grill", "Barbacoa", "Parrilla", "Asador", "Rustidera", "Cocotte", "Tajine", "Olla a presión", "Olla de cocción lenta", "Vaporeira", "Freidora", "Freidora de aire", "Batidora de mano", "Batidora de vaso", "Batidora amasadora", "Robot de cocina", "Licuadora", "Extractor de zumos", "Picadora", "Molinillo", "Cafetera", "Tetera", "Hervidor", "Tostadora", "Sandwichera", "Gofrera", "Crepera", "Yogurtera", "Heladera", "Panificadora"]
    },
    "Películas y series": {
        "easy": ["Titanic", "Star Wars", "Harry Potter", "El Rey León", "Toy Story", "Frozen", "Shrek", "Spider-Man", "Batman", "Los Vengadores", "Piratas del Caribe", "Jurassic Park", "Avatar", "Jumanji", "Solo en Casa", "Friends", "Los Simpson", "Juego de Tronos", "La Casa de Papel", "Stranger Things", "El Juego del Calamar", "Breaking Bad", "The Walking Dead", "The Big Bang Theory", "Cómo conocí a vuestra madre"],
        "medium": ["El Padrino", "Matrix", "Forrest Gump", "Pulp Fiction", "El Señor de los Anillos", "Gladiator", "Braveheart", "Rocky", "Terminator", "Alien", "Tiburón", "El Resplandor", "Psicosis", "Casablanca", "Indiana Jones", "Regreso al Futuro", "E.T.", "The Office", "Parks and Recreation", "Seinfeld", "Frasier", "Cheers", "M*A*S*H", "The Sopranos", "The Wire"],
        "hard": ["Ciudadano Kane", "2001: Una Odisea del Espacio", "Blade Runner", "Apocalypse Now", "La Naranja Mecánica", "El Club de la Lucha", "Origen", "Parásitos", "La Lista de Schindler", "Cadena Perpetua", "El Silencio de los Corderos", "Fargo", "No es País para Viejos", "Pozos de Ambición", "La Red Social", "Boyhood", "Birdman", "Whiplash", "La La Land", "Moonlight", "Roma", "El Gran Hotel Budapest", "Her", "Memento", "Donnie Darko", "Mulholland Drive", "El Viaje de Chihiro", "La Princesa Mononoke", "Akira", "Oldboy", "Amélie", "La Vida es Bella", "Cinema Paradiso", "Ladrón de Bicicletas", "El Séptimo Sello", "Stalker", "8½", "La Dolce Vita", "El Gatopardo", "Aguirre, la Cólera de Dios", "París, Texas", "Deseando Amar", "Ciudad de Dios", "Amores Perros", "El Laberinto del Fauno", "El Secreto de sus Ojos", "Relatos Salvajes", "Drive", "The Master", "Under the Skin", "Langosta", "Déjame Salir", "Hereditary", "Midsommar", "El Faro", "Mad Men", "Six Feet Under", "Deadwood", "The Leftovers", "Fleabag", "Chernobyl", "When They See Us", "The Crown", "Peaky Blinders", "Black Mirror", "Westworld", "Succession", "Better Call Saul", "Ozark", "Mindhunter", "Narcos", "The Mandalorian", "The Boys", "Invincible", "Arcane", "BoJack Horseman", "Rick and Morty", "Avatar: La Leyenda de Aang", "Fullmetal Alchemist: Brotherhood", "Death Note", "Ataque a los Titanes", "Cowboy Bebop", "Neon Genesis Evangelion", "Steins;Gate", "Code Geass", "Monster", "Vinland Saga", "Jujutsu Kaisen", "Kimetsu no Yaiba", "One Punch Man", "My Hero Academia", "Haikyuu!!", "JoJo's Bizarre Adventure", "Hunter x Hunter", "Gintama", "Clannad", "Your Lie in April", "Anohana", "Violet Evergarden", "Made in Abyss", "The Promised Neverland", "Erased", "Psycho-Pass", "Mushishi", "Natsume's Book of Friends", "March Comes in Like a Lion", "Showa Genroku Rakugo Shinju", "Ping Pong the Animation", "The Tatami Galaxy", "Keep Your Hands Off Eizouken!", "Odd Taxi", "Sonny Boy"]
    },
    "Música y bandas": {
        "easy": ["Pop", "Rock", "Rap", "Jazz", "Guitarra", "Piano", "Batería", "Voz", "Canción", "Concierto", "Festival", "Radio", "Disco", "Vinilo", "CD", "Queen", "The Beatles", "Michael Jackson", "Madonna", "Elvis Presley", "Bob Marley", "U2", "Coldplay", "AC/DC", "Guns N' Roses"],
        "medium": ["Hip Hop", "Soul", "Funk", "R&B", "Reggae", "Ska", "Música clásica", "Ópera", "Flamenco", "Tango", "Salsa", "Cumbia", "Merengue", "Bachata", "Reguetón", "Música electrónica", "Techno", "House", "Trance", "Heavy Metal", "Punk", "Grunge", "Indie", "Folk", "Country"],
        "hard": ["Blues", "Góspel", "Bluegrass", "New Age", "World music", "K-Pop", "J-Pop", "Synth-pop", "Glam Rock", "Rock progresivo", "Rock psicodélico", "Rock sinfónico", "Power Metal", "Death Metal", "Black Metal", "Thrash Metal", "Doom Metal", "Gothic Metal", "Metalcore", "Nu Metal", "Hardcore", "Screamo", "Emo", "Pop punk", "Ska punk", "Rock and Roll", "Rockabilly", "Surf Rock", "Garage Rock", "Britpop", "Shoegaze", "Dream Pop", "Trip Hop", "Big Beat", "Breakbeat", "Jungle", "Drum and Bass", "Dubstep", "IDM", "Glitch", "Minimal", "Deep House", "Progressive House", "Tech House", "Electro", "Disco", "Italo Disco", "Eurodance", "Hi-NRG", "Dance-pop", "Bubblegum Pop", "Teen Pop", "Power Pop", "Art Pop", "Baroque Pop", "Chamber Pop", "Twee Pop", "Noise Pop", "Sadcore", "Slowcore", "Post-rock", "Math Rock", "Krautrock", "Stoner Rock", "Southern Rock", "Heartland Rock", "Jangle Pop", "College Rock", "Lo-fi", "Chillwave", "Vaporwave", "Witch House", "Seapunk", "Trap", "Drill", "Boom Bap", "G-Funk", "Jazz Rap", "Conscious Hip Hop", "Gangsta Rap", "Crunk", "Mumble Rap", "SoundCloud Rap", "Abstract Hip Hop", "Instrumental Hip Hop", "Turntablism", "Freestyle", "Beatbox", "Spoken Word", "Poetry Slam", "A capela", "Canto gregoriano", "Madrigal", "Motete", "Oratorio", "Cantata", "Sinfonía", "Concierto", "Sonata", "Suite", "Fuga", "Canon", "Música de cámara", "Cuarteto de cuerda", "Quinteto de viento", "Orquesta", "Banda de música", "Coro", "Solista", "Dúo", "Trío", "Cuarteto", "Quinteto", "Sexteto", "Septeto", "Octeto", "Noneto", "Deceto", "Big band", "Marching band", "Brass band", "Steel band", "Gamelán", "Mariachi", "Tuna", "Rondalla", "Charanga", "Murga", "Comparsa", "Chirigota", "Coro rociero", "Orquesta de pulso y púa"]
    },
    "Escuela y educación": {
        "easy": ["Lápiz", "Libro", "Mesa", "Silla", "Pizarra", "Profesor", "Alumno", "Clase", "Recreo", "Examen", "Deberes", "Nota", "Aprobar", "Suspender", "Mochila", "Estuche", "Goma", "Sacapuntas", "Regla", "Tijera", "Pegamento", "Cuaderno", "Carpeta", "Folio", "Bolígrafo"],
        "medium": ["Universidad", "Instituto", "Colegio", "Guardería", "Biblioteca", "Laboratorio", "Gimnasio", "Comedor", "Patio", "Aula", "Asignatura", "Horario", "Calendario", "Vacaciones", "Puente", "Fiesta", "Graduación", "Diploma", "Título", "Beca", "Matrícula", "Secretaría", "Dirección", "Conserjería", "Ampa"],
        "hard": ["Tesis", "Doctorado", "Máster", "Grado", "Licenciatura", "Diplomatura", "Formación profesional", "Bachillerato", "ESO", "Primaria", "Infantil", "Parvulario", "Claustro", "Paraninfo", "Salón de actos", "Cátedra", "Departamento", "Facultad", "Campus", "Residencia", "Colegio mayor", "Tuna", "Novatada", "Erasmus", "Intercambio", "Prácticas", "Beca Séneca", "Beca Fulbright", "Beca Erasmus Mundus", "Crédito ECTS", "Trabajo de fin de grado", "Trabajo de fin de máster", "Tesis doctoral", "Tribunal", "Defensa", "Cum laude", "Sobresaliente", "Notable", "Bien", "Suficiente", "Insuficiente", "Matrícula de honor", "Expediente", "Currículum", "Portfolio", "Carta de recomendación", "Carta de motivación", "Admisión", "Preinscripción", "Selectividad", "PAU", "EBAU", "EvAU", "PCE", "Acceso a la universidad", "Nota de corte", "Ponderación", "Parámetro", "Asignatura troncal", "Asignatura específica", "Asignatura optativa", "Asignatura de libre configuración", "Seminario", "Taller", "Conferencia", "Congreso", "Simposio", "Jornada", "Curso de verano", "MOOC", "Curso online", "E-learning", "B-learning", "Gamificación", "Aprendizaje basado en proyectos", "Aprendizaje cooperativo", "Aprendizaje servicio", "Clase magistral", "Lección", "Ponencia", "Comunicación", "Póster", "Artículo", "Publicación", "Revista científica", "Índice de impacto", "Factor de impacto", "Cita", "Referencia", "Bibliografía", "Plagio", "Honestidad académica", "Ética", "Deontología", "Investigación", "Desarrollo", "Innovación", "Transferencia", "Divulgación", "Ciencia", "Tecnología", "Ingeniería", "Artes", "Humanidades", "Ciencias sociales", "Ciencias de la salud", "Ciencias jurídicas"]
    },
    "Ciencia y tecnología": {
        "easy": ["Rueda", "Fuego", "Luz", "Agua", "Aire", "Tierra", "Sol", "Luna", "Estrella", "Planeta", "Átomo", "Célula", "Gen", "ADN", "Virus", "Bacteria", "Electricidad", "Imán", "Motor", "Máquina", "Herramienta", "Teléfono", "Ordenador", "Internet", "Robot"],
        "medium": ["Gravedad", "Energía", "Materia", "Velocidad", "Aceleración", "Fuerza", "Masa", "Peso", "Volumen", "Densidad", "Temperatura", "Presión", "Sonido", "Eco", "Reflejo", "Refracción", "Lente", "Espejo", "Prisma", "Arcoíris", "Molécula", "Compuesto", "Elemento", "Reacción", "Evolución"],
        "hard": ["Agujero negro", "Cuántico", "Relatividad", "Big Bang", "Materia oscura", "Energía oscura", "Supernova", "Púlsar", "Cuásar", "Magnetar", "Ondas gravitacionales", "Entrelazamiento cuántico", "Teletransporte cuántico", "Computación cuántica", "Criptografía cuántica", "Superconductividad", "Superfluidez", "Bose-Einstein", "Fermión", "Bosón", "Quark", "Leptón", "Neutrino", "Muón", "Tauón", "Gluón", "Fotón", "Gravitón", "Bosón de Higgs", "Teoría de cuerdas", "Teoría M", "Multiverso", "Brana", "Dimensión", "Espaciotiempo", "Gusano", "Paradoja", "Singularidad", "Horizonte de sucesos", "Radiación de Hawking", "Inflación cósmica", "Fondo cósmico de microondas", "Nucleosíntesis", "Fusión nuclear", "Fisión nuclear", "Radiación", "Isótopo", "Vida media", "Acelerador de partículas", "Colisionador", "CERN", "LHC", "Detector", "Cámara de niebla", "Cámara de burbujas", "Contador Geiger", "Escintilador", "Fotodetector", "Espectrómetro", "Cromatógrafo", "Microscopio", "Telescopio", "Radiotelescopio", "Interferómetro", "Láser", "Máser", "LED", "OLED", "LCD", "Plasma", "Grafeno", "Nanotubo", "Fullereno", "Metamaterial", "Aerogel", "Cristal líquido", "Polímero", "Plástico", "Fibra de carbono", "Fibra óptica", "Semiconductor", "Transistor", "Circuito integrado", "Chip", "Microprocesador", "Memoria RAM", "Memoria ROM", "Disco duro", "SSD", "USB", "Bluetooth", "Wifi", "5G", "GPS", "Satélite", "Sonda espacial", "Cohete", "Transbordador", "Estación espacial", "Inteligencia artificial", "Aprendizaje automático", "Red neuronal", "Algoritmo", "Big data", "Nube", "Ciberseguridad", "Hacking", "Malware", "Virus", "Troyano", "Ransomware", "Phishing", "Firewall", "VPN", "Blockchain", "Criptomoneda", "Bitcoin", "Ethereum", "NFT", "Biotecnología", "Ingeniería genética", "CRISPR", "Clonación", "Célula madre", "Terapia génica", "Prótesis", "Implante", "Marcapasos", "Resonancia magnética", "Tomografía", "Radiografía", "Ecografía", "Endoscopia", "Laparoscopia", "Cirugía robótica"]
    },
    "Transporte": {
        "easy": ["Coche", "Bici", "Avión", "Barco", "Tren", "Autobús", "Moto", "Camión", "Taxi", "Metro", "Patinete", "Monopatín", "Patin", "Andar", "Correr", "Saltar", "Nadar", "Volar", "Navegar", "Conducir", "Viajar", "Rueda", "Motor", "Vela", "Remo"],
        "medium": ["Helicóptero", "Globo aerostático", "Submarino", "Cohete", "Nave espacial", "Tractor", "Excavadora", "Grúa", "Ambulancia", "Policía", "Bomberos", "Furgoneta", "Caravana", "Remolque", "Quad", "Moto de nieve", "Moto de agua", "Lancha", "Yate", "Velero", "Canoa", "Kayak", "Ferry", "Crucero", "Tranvía"],
        "hard": ["Dirigible", "Zepelín", "Hidroavión", "Ultraligero", "Ala delta", "Parapente", "Monorraíl", "Funicular", "Teleférico", "Telesilla", "Tren de alta velocidad", "Tren magnético", "Carruaje", "Diligencia", "Trineo", "Sidecar", "Tuk-tuk", "Bicitaxi", "Segway", "Hoverboard", "Monociclo eléctrico", "Catamarán", "Trimarán", "Góndola", "Balsa", "Transatlántico", "Portaaviones", "Destructor", "Fragata", "Corbeta", "Acorazado", "Dragaminas", "Petrolero", "Carguero", "Pesquero", "Rompehielos", "Caza", "Bombardero", "Dron", "Satélite", "Sonda espacial", "Estación espacial", "Transbordador", "Apolo", "Soyuz", "Falcon", "Ariane", "Vega", "Atlas", "Delta", "Protón", "Larga Marcha", "GSLV", "H-IIA", "Angara", "Vulcan", "New Shepard", "Starship", "Dream Chaser", "Orion", "Starliner", "Dragon", "Cygnus", "Progress", "ATV", "HTV", "Skylab", "Mir", "Salyut", "Tiangong", "ISS", "Gateway", "Lunar Gateway", "Artemis", "Mariner", "Pioneer", "Viking", "Voyager", "Galileo", "Cassini", "Huygens", "Juno", "New Horizons", "OSIRIS-REx", "Hayabusa", "Rosetta", "Philae", "Beagle 2", "Sojourner", "Spirit", "Opportunity", "Curiosity", "Perseverance", "Ingenuity", "Zhurong", "Yutu", "Chandrayaan", "Beresheet", "Hakuto-R", "SLIM", "Venera", "Vega", "Marte", "Venus", "Mercurio", "Júpiter", "Saturno", "Urano", "Neptuno", "Plutón", "Ceres", "Eris", "Makemake", "Haumea", "Sedna", "Quaoar", "Orcus", "Gonggong", "Salacia", "Varda", "Ixion", "Varuna"]
    },
    "Clima y naturaleza": {
        "easy": ["Sol", "Lluvia", "Nube", "Viento", "Nieve", "Río", "Mar", "Lago", "Montaña", "Árbol", "Flor", "Hierba", "Piedra", "Arena", "Tierra", "Cielo", "Día", "Noche", "Calor", "Frío", "Humedad", "Sequía", "Inundación", "Tormenta", "Rayo"],
        "medium": ["Arcoíris", "Niebla", "Granizo", "Relámpago", "Trueno", "Tornado", "Huracán", "Tsunami", "Terremoto", "Volcán", "Glaciar", "Desierto", "Bosque", "Selva", "Sabana", "Tundra", "Estepa", "Pradera", "Marisma", "Pantano", "Manglar", "Arrecife", "Coral", "Alga", "Musgo"],
        "hard": ["Aurora boreal", "Eclipse", "Cometa", "Meteorito", "Géiser", "Avalancha", "Monzón", "Ciclón", "Anticiclón", "Borrasca", "Frente frío", "Frente cálido", "Frente ocluido", "Frente estacionario", "Gota fría", "DANA", "Calima", "Brisa", "Terral", "Levante", "Poniente", "Cierzo", "Tramontana", "Mistral", "Siroco", "Föhn", "Chinook", "Zonda", "Alisio", "Contralisio", "Célula de Hadley", "Célula de Ferrel", "Célula polar", "Corriente en chorro", "Efecto Coriolis", "Efecto invernadero", "Calentamiento global", "Cambio climático", "El Niño", "La Niña", "Oscilación del Atlántico Norte", "Oscilación del Sur", "Erosión", "Sedimentación", "Meteorización", "Tectónica de placas", "Deriva continental", "Subducción", "Orogénesis", "Falla", "Pliegue", "Magma", "Lava", "Ceniza", "Piroclasto", "Lahar", "Fumarola", "Solfa", "Mofeta", "Cráter", "Caldera", "Domo", "Cono", "Escudo", "Estratovolcán", "Supervolcán", "Punto caliente", "Dorsal oceánica", "Fosa abisal", "Plataforma continental", "Talud continental", "Llanura abisal", "Guyot", "Atolón", "Isla barrera", "Fiordo", "Ría", "Estuario", "Delta", "Meandro", "Afluente", "Cuenca", "Caudal", "Nacimiento", "Desembocadura", "Acuífero", "Manantial", "Cascada", "Catarata", "Rápido", "Remanso", "Poza", "Vado", "Ribera", "Orilla", "Playa", "Acantilado", "Cabo", "Golfo", "Bahía", "Ensenada", "Estrecho", "Canal", "Península", "Istmo", "Archipiélago", "Isla", "Islote", "Cayo", "Farallón", "Escollo", "Bajo", "Banco de arena", "Duna", "Oasis", "Salina", "Salar", "Chott", "Wadi", "Badlands", "Cárcava", "Humedal", "Turbera", "Ciénaga", "Laguna", "Charca", "Estanque", "Embalse", "Presa"]
    }
};
