const wordCategories = {
  "Animales": ["Perro", "Gato", "Elefante", "León", "Jirafa", "Tigre", "Oso", "Pingüino", "Mono", "Cebra"],
  "Comidas": ["Pizza", "Hamburguesa", "Sushi", "Taco", "Ensalada", "Pasta", "Sopa", "Helado", "Paella", "Curry"],
  "Frutas": ["Manzana", "Plátano", "Fresa", "Naranja", "Uva", "Piña", "Mango", "Sandía", "Kiwi", "Pera"],
  "Profesiones": ["Médico", "Profesor", "Bombero", "Policía", "Ingeniero", "Artista", "Chef", "Piloto", "Abogado", "Científico"],
  "Deportes": ["Fútbol", "Baloncesto", "Tenis", "Béisbol", "Natación", "Voleibol", "Golf", "Boxeo", "Ciclismo", "Atletismo"],
  "Países": ["España", "México", "Argentina", "Japón", "Italia", "Canadá", "Brasil", "Australia", "Egipto", "China"],
  "Instrumentos Musicales": ["Guitarra", "Piano", "Violín", "Batería", "Trompeta", "Flauta", "Saxofón", "Arpa", "Bajo", "Acordeón"],
  "Vehículos": ["Coche", "Bicicleta", "Avión", "Barco", "Tren", "Motocicleta", "Autobús", "Helicóptero", "Submarino", "Camión"],
  "Colores": ["Rojo", "Azul", "Verde", "Amarillo", "Naranja", "Morado", "Negro", "Blanco", "Rosa", "Marrón"],
  "Partes del Cuerpo": ["Cabeza", "Brazo", "Pierna", "Ojo", "Nariz", "Boca", "Mano", "Pie", "Corazón", "Cerebro"],
  "Ropa": ["Camisa", "Pantalón", "Vestido", "Zapato", "Sombrero", "Chaqueta", "Falda", "Calcetines", "Gafas", "Guantes"],
  "Objetos de la Casa": ["Silla", "Mesa", "Cama", "Sofá", "Lámpara", "Televisión", "Espejo", "Reloj", "Armario", "Nevera"],
  "Fenómenos Naturales": ["Lluvia", "Nieve", "Viento", "Sol", "Terremoto", "Tornado", "Huracán", "Volcán", "Arcoíris", "Tsunami"],
  "Películas Famosas": ["Titanic", "Star Wars", "Jurassic Park", "El Padrino", "Avatar", "Matrix", "Forrest Gump", "Pulp Fiction", "E.T.", "Casablanca"],
  "Superhéroes": ["Superman", "Batman", "Spiderman", "Iron Man", "Capitán América", "Thor", "Hulk", "Wonder Woman", "Aquaman", "Flash"],
  "Herramientas": ["Martillo", "Destornillador", "Sierra", "Taladro", "Llave inglesa", "Alicates", "Cinta métrica", "Nivel", "Tornillo", "Clavo"],
  "Bebidas": ["Agua", "Café", "Té", "Leche", "Jugo", "Refresco", "Vino", "Cerveza", "Limonada", "Chocolate caliente"],
  "Planetas del Sistema Solar": ["Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno"],
  "Figuras Geométricas": ["Círculo", "Cuadrado", "Triángulo", "Rectángulo", "Pentágono", "Hexágono", "Estrella", "Cubo", "Esfera", "Cilindro"],
  "Emociones": ["Alegría", "Tristeza", "Enojo", "Miedo", "Sorpresa", "Amor", "Asco", "Vergüenza", "Orgullo", "Calma"]
};
